perl /homes/liu3zhen/local/slurm/trimmomatic/trimmomatic.sbatch.pl \
	--mem 6G \
	--time 18:00:00 \
	--trim_shell "/homes/liu3zhen/local/pipelines/trimmomatic/trimmomatic.pe.sh" \
	--trimmomatic "/homes/liu3zhen/local/jars/trimmomatic-0.38.jar" \
	--adaptor_file "/homes/liu3zhen/local/pipelines/trimmomatic/trimmomatic_adaptDB/TruSeq3-PE.fa" \
	--indir "../0_raw" \
	--outdir "." \
	--fq1feature "_1.fq.gz" \
	--fq2feature "_2.fq.gz" \
	--threads 4 \
	--min_len 60
